name: app_compras
description: Control de Gastos - AplicaciÃ³n para gestionar gastos personales
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  table_calendar: ^3.0.9
  pdf: ^3.10.7
  printing: ^5.12.0
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "android/app/src/main/res/drawable/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "android/app/src/main/res/drawable/logo.png"
